# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_id', models.IntegerField(blank=True, null=True)),
                ('book_time', models.DateField(blank=True, null=True)),
                ('book_idnum', models.CharField(blank=True, max_length=18, null=True)),
                ('book_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('book_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='Checkinfo',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('check_name', models.CharField(blank=True, max_length=16, null=True)),
                ('check_idnum', models.CharField(blank=True, max_length=18, null=True)),
                ('check_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('check_leavetime', models.DateField(blank=True, null=True)),
                ('check_checkintime', models.DateField(blank=True, db_column='check_checkInTime', null=True)),
                ('check_statu', models.CharField(blank=True, max_length=5, null=True)),
                ('room_id', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'checkinfo',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(blank=True, max_length=16, null=True)),
                ('cus_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('cus_password', models.CharField(blank=True, max_length=20, null=True)),
                ('id_num', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_level', models.CharField(blank=True, max_length=11, null=True)),
                ('room_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('room_level', models.CharField(blank=True, max_length=11, null=True)),
                ('room_pic', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sta_id', models.AutoField(primary_key=True, serialize=False)),
                ('sta_authority', models.CharField(blank=True, max_length=6, null=True)),
                ('sta_passward', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'staff',
            },
        ),
    ]
